import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { solarizedDarkAtom } from 'react-syntax-highlighter/dist/esm/styles/prism';

export default function DayOne() {
  const codeExample = `{
  "type": "tool_use",
  "id": "toolu_01EeLhMxuaKi93tZuTiW3t1o",
  "name": "create_chart",
  "input": {
    "id": "browser_distribution",
    "type": "Pie",
    "datasetId": "vercel",
    "apl": "vercel\n| summarize count() by browser"
  }
}`;

  return (
    <article>
      <div className="mb-24 text-center">
        <time className="text-gray-400 text-md ">March 25, 2025</time>
        <h1 className="text-2xl font-bold mt-2 mb-4 text-gray-200">Day one</h1>
      </div>

      <a href="https://www.loom.com/share/cecfb37c16c541aa9a3956e41707ed85">
        <img src="https://cdn.loom.com/sessions/thumbnails/cecfb37c16c541aa9a3956e41707ed85-4840d42e9dfcd433-full-play.gif"  className="w-full" />
      </a>
      
      <img 
        src="/posts/day1/luna-plan.png"  
        alt="Project plan"
        className="w-full rounded-lg my-8"
      />

      <div className="prose prose-invert prose-lg max-w-none">
        <p className="text-gray-300 leading-relaxed mb-6">
          Luna started exploring using Claude to generate APL that could be used to create charts in <strong>Axiom</strong> dashboards.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-white">Making progress!</h2>
        <p className="text-gray-300 leading-relaxed mb-6">
          Using the prompt <strong>"a chart for browsers in the 'vercel' dataset"</strong>, Claude was able to generate a chart!
        </p>
        <div className="my-6">
          <SyntaxHighlighter
            language="javascript"
            style={solarizedDarkAtom}
            className="rounded-lg"
            customStyle={{
              backgroundColor: '#1E1E1E',
            }}
          >
            {codeExample}
          </SyntaxHighlighter>
        </div>

        <img 
          src="/posts/day1/first-chart.png"  
          alt="First chart generated by AI"
          className="w-full  object-cover rounded-lg my-8"
        />
        
        <div className="my-6">
        <p className="text-gray-300 leading-relaxed mb-6">
          Derek started working on some UI things &amp; trying to fix the chart preview. He's also thinking about adding a <strong><em>YOLO</em></strong> mode, and the option to continue editing the chart in the sidebar editor.
        </p>
        </div>

        <img 
          src="/posts/day1/derek-2.png"  
          alt="Chart preview in AI modal"
          className="w-full  object-cover rounded-lg my-8"
        />

      </div>
    </article>
  )
}